[env:radiomaster_dbr4]
custom_meshtastic_hw_model = 139
custom_meshtastic_hw_model_slug = RADIOMASTER_DBR4
custom_meshtastic_architecture = esp32
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = RadioMaster DBR4
custom_meshtastic_tags = RadioMaster

extends = esp32_base
board = pico32
board_level = extra
board_build.f_flash = 80000000L
build_flags =
  ${esp32_base.build_flags}
  -DRADIOMASTER_DBR4
  -DVTABLES_IN_FLASH=1
  -DCONFIG_DISABLE_HAL_LOCKS=1
  -DMESHTASTIC_EXCLUDE_I2C=1
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR_EXTERNAL=1
  -DMESHTASTIC_EXCLUDE_AIR_QUALITY_SENSOR=1
  -O2
  -I variants/esp32/radiomaster_dbr4
build_src_filter =
  ${esp32_base.build_src_filter}
  +<../variants/esp32/radiomaster_dbr4>
board_build.f_cpu = 240000000L
upload_protocol = esptool
upload_speed = 460800
