name: CI
concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
      - master
      - develop
      - pioarduino
      - event/*
      - feature/*
    paths-ignore:
      - "**.md"
      - version.properties

  pull_request:
    branches:
      - master
      - develop
      - pioarduino
      - event/*
      - feature/*
    paths-ignore:
      - "**.md"

  workflow_dispatch:

permissions: read-all

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get release version string
        run: |
          echo "long=$(./bin/buildinfo.py long)" >> $GITHUB_OUTPUT
        id: version
        env:
          BUILD_LOCATION: local
    outputs:
      long: ${{ steps.version.outputs.long }}

  build:
    needs: [version]
    strategy:
      fail-fast: false
      matrix:
        build:
          - { board: "heltec-v4",            platform: "esp32s3" }
          - { board: "betafpv_2400_tx_micro", platform: "esp32"   }
          - { board: "radiomaster_nomad",     platform: "esp32"   }
    uses: ./.github/workflows/build_firmware.yml
    with:
      version: ${{ needs.version.outputs.long }}
      pio_env: ${{ matrix.build.board }}
      platform: ${{ matrix.build.platform }}
